### ISSUE TITLE
GTK 3 Compatibility

### ISSUE THREAD

**Issue by wmvanvliet** [chimara/Chimara#11]
> Originally Trac #5

Rewrite relevant portions in GTK 3

**Comment by ptomato** [comment]
@ptomato commented 2011-08-08:

> Oh, man! I just saw this! 
> ​http://developer.gnome.org/gtk3/unstable/GtkOverlay.html
> The pager is going to be _so_ much more simple in GTK 3.2!

@ptomato commented 2012-09-16:

> Only thing left to do:
> Use GTK3's CSS styling facilities.

**Comment by ptomato** [comment]
Also, remove use of `gdk_threads_enter()` and `gdk_threads_leave()`.
