### ISSUE TITLE
Trinity title screen offset wrong

### ISSUE THREAD

**Issue by wmvanvliet** [chimara/Chimara#5]
> Originally Trac #11

Title screen seems to appear in the area reserved for the status bar so causes problems for the scroll bar. (screenshot-001) There should be no scroll bar on this screen.

May be a bug in text grids, but I rather suspect it's a bug in GlkFrotz.

To reproduce screen shot: (SPOILER WARNING!)
e; get soccer ball; nw; look at sundial; look at gnomon; unscrew gnomon; get it; ne; n; help woman; throw soccer ball at umbrella; get umbrella; w; w; open pram; push pram south; buy crumbs; get bag and change; put coin in pocket; feed birds; get ruby; push pram east; look at boats; get paper bird; unfold it; read it; look at watch; push pram east; get in pram; open umbrella; get all; look at statue; look at watch; look at missile; e; enter door.

**Comment by ptomato** [comment]
@ptomato commented 2011-02-06:

> Screen shot of "Trinity" title screen

![image](https://cloud.githubusercontent.com/assets/459371/13211212/3b6dbfdc-d8eb-11e5-93e7-4598381a3b37.png)

*Ezekiel000* commented 2011-02-06:

> Better in the latest build but still not perfect.

![image](https://cloud.githubusercontent.com/assets/459371/13211229/65966fac-d8eb-11e5-9bdb-331f56ae9302.png)

*Ezekiel000* commented 2011-11-07:

> The " displayed to the bottom left of the title shouldn't be there.

@wmvanvliet commented 2012-09-16:

> Bug in Trinity game itself. Some text is not shown at all, since game immediately requests a `glk_window_clear()`.

@wmvanvliet closed 2012-09-16
