### ISSUE TITLE
Load preferences from file

### ISSUE THREAD

**Issue by wmvanvliet** [chimara/Chimara#6]
> Originally Trac #1

Create user preferences file for the chimara player

Find it in:

```
~/.chimara/config
./config
$PREFIX/etc/chimara/config
```

**Comment by ptomato** [comment]
@ptomato commented on 2011-02-28T01:04:45+01:00
> For preferences, I think we ought to use, in this order:
> - `./chimara-config` (in case there are any other files lying around named `config`)
> - `~/.chimara/config`
> - system defaults, not in `/etc/`, but implemented as default values in a GSettings schema
