### ISSUE TITLE
Support new vesion of the GLK spec

### ISSUE THREAD

**Issue by wmvanvliet** [chimara/Chimara#7]
> Originally Trac #2

implement new features as described in:
http://www.eblong.com/zarf/glk/

**Comment by ptomato** [comment]
@ptomato commented 2011-02-20:
> Version 0.7.2, with date-time functions, was released the other day.

@ptomato commented 2011-04-20:
> Stubs for all the new functions are added, so strictly speaking we support the spec version 0.7.2. Now to actually write the implementations - I won't close this until that is done.

@ptomato closed 2011-05-01
