### ISSUE TITLE
Create preferences dialog for player

### ISSUE THREAD

**Issue by wmvanvliet** [chimara/Chimara#8]
> Originally Trac #3

Implement a GUI for changing preferences for the player on the fly.

**Comment by ptomato** [comment]
@ptomato commented 2011-03-13:
> I think the preferences dialog is quite decent for now, so I'm closing this bug. There are still some things to do:
> - the CSS editor, which I have disabled for now and will open another bug for
> - think of some general settings to put in the first panel, instead of flepping while gronking a bloop - but I think this will follow naturally after we write the library browser!

@ptomato closed 2011-03-13
